kuvagalleria/galleria/urls.py
from django.urls import path, include
from . import views
from register.views import register_view
from login.views import signin, signout
from django.contrib import admin

app_name = 'galleria'

urlpatterns = [
    path('', views.index, name='index'),
    path('images/<int:pk>', views.imagepage, name='imagepage'),
    path('profile/<str:user>', views.profilepage, name='profile'),
    path('upload/', views.uploadpage, name='upload'),
    path('search/', views.search, name='search'),
    path('register/', register_view, name='register'),
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),
]

kuvagalleria/kuvagalleria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('galleria.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kuvagalleria/login/urls.py
from django.urls import path
from login.views import signin, home_view

urlpatterns = [
    path('', home_view, name="main"),
    path('login/', signin, name="login")
]

kuvagalleria/galleria/models.py
from django.db import models
from django.contrib.auth.models import User
import os.path
from PIL import Image as pillowImage
from io import BytesIO
from django.core.files.base import ContentFile

# Create your models here.

def get_upload_path(instance, filename):
    return "%s/%s/%s" % (instance.user, instance.subfolder, filename)


class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    subfolder = models.CharField(max_length=20, blank=True)
    title = models.CharField(max_length=20, null=False)
    private = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    description = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to=get_upload_path)
    full_hd = models.ImageField(upload_to=get_upload_path, null=True)
    thumbnail = models.ImageField(upload_to=get_upload_path, editable=False)
    aspect_ratio = models.FloatField()
    def save(self, *args, **kwargs):

        if not self.thumbnail:
            self.make_thumbnail()
        
        if self.check_if_full_hd() and not self.full_hd:
            self.make_full_hd()

        super(Image, self).save(*args, **kwargs)

    def check_if_full_hd(self):
        im_size = pillowImage.open(self.image)
        width, height = im_size.size
        if width <= 1920 or height <= 1080:
            return False
        else:
            return True

    def make_full_hd(self):
        file, ext = os.path.splitext(self.image.name)
        im = pillowImage.open(self.image)
        im.thumbnail((1920, 1920), pillowImage.ANTIALIAS)
        ext = ext.lower()
        
        if ext in [".jpg", ".jpeg"]:
            filetype = "JPEG"
        elif ext == ".gif":
            filetype = "GIF"
        elif ext == ".png":
            filetype = "PNG"
        else:
            return
        buf = BytesIO()
        im.save(buf, filetype)
        buf.seek(0)
        self.full_hd.save(file+"_full_hd"+ext, ContentFile(buf.read()))
        buf.close()
        return


    def make_thumbnail(self):

        file, ext = os.path.splitext(self.image.name)
        im = pillowImage.open(self.image)

        # save image aspect ratio
        width, height = im.size
        aspect_ratio = width/height
        self.aspect_ratio = aspect_ratio

        im.thumbnail((500,500), pillowImage.ANTIALIAS)
        ext = ext.lower()
        
        if ext in [".jpg", ".jpeg"]:
            filetype = "JPEG"
        elif ext == ".gif":
            filetype = "GIF"
        elif ext == ".png":
            filetype = "PNG"
        else:
            return
        buf = BytesIO()
        im.save(buf, filetype)
        buf.seek(0)
        self.thumbnail.save(file+"_thumbnail"+ext, ContentFile(buf.read()))
        buf.close()
        return

    @property
    def fullhdURL(self):
        try:
            url = self.full_hd.url
        except:
            url = ""
        return url

    @property
    def thumbnailURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ""
        return url

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url

    def __str__(self):
        return self.title

kuvagalleria/galleria/forms.py
from django import forms
from .models import Image
from django.core.validators import RegexValidator

class ImageForm(forms.ModelForm):
    subfolder = forms.CharField(required=False, validators=[RegexValidator('^\w+$', message="Subfolder name can only contain alphanumeric characters")])
    class Meta:
        model = Image
        fields = ['title', 'subfolder', 'image', 'private', 'description' ]

kuvagalleria/galleria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Image
from .forms import ImageForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    return redirect('register/register/')

def login(request):
    return redirect('login/login/')

def index(request):
    sortTerm = request.GET.get('sort', None)
    if sortTerm == None:
        images = Image.objects.filter(private=False)
    else:
        if sortTerm == 'views' or sortTerm == 'rating':
            images = Image.objects.filter(private=False).order_by(sortTerm).reverse()
        elif sortTerm == 'newest':
            images = Image.objects.filter(private=False).order_by('date', 'time').reverse()
        elif sortTerm == 'oldest':
            images = Image.objects.filter(private=False).order_by('date','time')
        else:
            images = Image.objects.filter(private=False).order_by(sortTerm)

    context = {"images": images}
    return render(request, "galleria/frontpage.html", context)

def search(request):
    searchTerm = request.GET.get('search', '')

    # print('searchterm', searchTerm)
    if searchTerm == None:
        images = Image.objects.filter(private=False)
    else:
        images = Image.objects.filter(private=False, title__contains=searchTerm)

    context = {"images": images}
    return render(request, "galleria/search_page.html", context)

def imagepage(request, pk):
    image = get_object_or_404(Image, pk=pk)
    if image.private == True:
        print(image.user)
        if image.user != request.user:
            return redirect('/')
    
    if request.method == "POST":
        if 'delete' in request.POST:
            if user_authorized(request.user, image.user.username):
                image.delete()
                return redirect('galleria:index')
                

        if 'vote' in request.POST:
            if user_authorized(request.user, image.user.username):
                print('not allowed')
                return redirect("galleria:imagepage", image.id)
            else: 
                image.rating += 1
    
    image.views = image.views + 1
    image.save()
    context = {"image": image}
    return render(request, "galleria/image_page.html", context)


@login_required
def profilepage(request, user):
    # Check if currently logged in user is the owner
    if not user_authorized(request.user, user):
        return redirect("/")

    # Get users pictures and subfolders
    images = Image.objects.filter(user=request.user).order_by('subfolder')
    folders = []
    likes = 0
    views = 0
    for x in images:
        likes += x.rating
        views += x.views
        if x.subfolder not in folders:
            folders.append(x.subfolder)
    print(folders)
    context = {"images": images, "folders": folders, 'likes': likes, 'views': views}

    return render(request, "galleria/profile_page.html", context)


@login_required
def uploadpage(request):
    imageForm = ImageForm()
    if request.method == "POST":
        imageForm = ImageForm(request.POST, request.FILES)
        if imageForm.is_valid():
            print("form is valid")
            image = imageForm.save(commit=False)
            image.user = request.user
            image.save()
            return redirect("galleria:profile", request.user)

    context = {"form": imageForm}

    return render(request, "galleria/upload_page.html", context)

def user_authorized(req_user, compare_to_user):
    username = str(req_user).lower()
    user = str(compare_to_user).lower()
    print(username)
    print(user)
    if username == user:
        print('Authorized')
        return True
    else:
        print('Not authorized')
        return False

kuvagalleria/galleria/templates/galleria/frontpage.html
{% extends 'galleria/main.html' %}
{% load static %}

{% block content %}
<div class='controls'>
    <div onclick='openSort()' id='sort' class='sort-btn'><img src="{% static 'galleria/sort.png' %}" alt="">
        <div class='sort-list' id='sort-list'>
            Sort by:
            <ul class='ul-sort'>
                <li ><a href="?sort=title">Title</a></li>
                <li><a href="?sort=newest">Newest</a></li>
                <li><a href="?sort=oldest">Oldest</a></li>
                <li><a href="?sort=rating">Rating</a></li>
                <li><a href="?sort=views">Views</a></li>
            </ul>
        </div>
    </div>
    <div style='background-color: #000000;' id='grid' onclick='setGrid()' class='layout-btn'><img src="{% static 'galleria/grid_64_64.png' %}" alt=""></div>
    <div id='vert' onclick='setVertical()' class='layout-btn'><img src="{% static 'galleria/vertical_64_64.png' %}" alt=""></div>
</div>
<div class="photo-grid" id='pg-frontpage'>
    {% for image in images %}
        {% if not image.full_hd %}
            <div class="card card-wide wide-card" style="background-image:url({{image.thumbnailURL}})">
                <strong>{{image.title}}</strong>
                <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
            </div>
        {% elif image.aspect_ratio > 1.9 %}
            <div class="card card-wide wide-card" style="background-image:url({{image.fullhdURL}})">
                <strong>{{image.title}}</strong>
                <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
            </div>
        {% elif image.aspect_ratio < 1.5 %}
            <div class="card card-tall tall-card" style="background-image:url({{image.fullhdURL}})">
                <strong>{{image.title}}</strong>
                <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
            </div>
        {% else %}
            <div class="card card-wide card-tall big-card" style="background-image:url({{image.fullhdURL}})">
                <strong>{{image.title}}</strong>
                <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
            </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock content %}

kuvagalleria/galleria/templates/galleria/image_page.html
{% extends 'galleria/main.html' %}
{% load static %}

{% block content %}

{% if user.username == image.user.username%}
<form method="post">{% csrf_token %}<button name='delete' class='delete-btn' type="submit">Poista</button></form>
{% endif %}


<div class="grid-container">
    <div class="photo-item"><img src={{image.imageURL}} class='photo-item-image' /></div>
    <div class="download-item">Download links<br><a href='{{ MEDIA_URL }}{{ image.imageURL }}'>Original</a>
        {% if image.full_hd %}
            <a href='{{ MEDIA_URL }}{{ image.fullhdURL }}'>Full HD</a>
        {% else %}
            <div>No full hd picture available</div>
        {% endif %}</div>
    
    <div class="details-item">Name: {{image.title}} <br> Upload Date: {{image.date}}</div>
    

    <div class="vote-item">
        {% if user == image.user or not user.is_authenticated  %}
            <img src="{% static 'galleria/thumbs_up.png' %}">
        {% else %}
            <form method='post' >{% csrf_token %}
                <button name='vote' type='submit' class='no-styling'>
                    <img  class='hover' src="{% static 'galleria/thumbs_up.png' %}" >
                </button>
            </form>
        {% endif %}
        Upvotes: {{image.rating}}
    </div>
</div>

{% endblock content %}

kuvagalleria/galleria/templates/galleria/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Galleria</title>
    <link rel="stylesheet" type="text/css" href="{% static 'galleria/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jscripts.js'%}" ></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'galleria:index' %}">KuvaGalleria</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'galleria:index' %}">Galleria <span class="sr-only">(current)</span></a>
        </li>
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'galleria:profile' user %}">Profile</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'galleria:upload' %}">Upload image</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'galleria:logout' %}">Sign out</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'galleria:login' %}">Sign in</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'galleria:register' %}">Sign up</a>
                </li>
            {% endif %}
        </ul>
            <div class="form-inline my-2 my-lg-0">
                <input id='search-field' class="form-control mr-sm-2" type="search" placeholder="Search by title" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" onclick="search()">Search</button>
            </div>
    </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
</body>

</html>

kuvagalleria/galleria/templates/galleria/profile_page.html
{% extends 'galleria/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <div class='profile-main'>
        <h2>{{user}} - Profile page</h2>
        <div class='statistics'>
            <div>Images: {{images|length}}</div>
            <div>Likes: {{likes}}</div>
            <div>Views: {{views}}</div>
        </div>
        
    </div>

    {% for folder in folders %}
    <h3 id=''>/{{folder}}</h3>
    <div class="profile-photo-grid">
        {% for image in images %}
        {% if image.subfolder == folder %}
        <div class="card" style="background-image:url({{image.thumbnailURL}})">
            <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
        </div>
        {% endif %}

        {% endfor %}
    </div>
    {% endfor %}

</div>

{% endblock content %}

kuvagalleria/galleria/templates/galleria/search_page.html
{% extends 'galleria/main.html' %}
{% load static %}

{% block content %}
<h2>Search results</h2>
<div class="photo-grid" id='pg-frontpage'>
    {% if images|length != 0 %}
    {% for image in images %}
            <div class="card" style="background-image:url({{image.thumbnailURL}})">
                <strong>{{image.title}}</strong>
                <a class='image-link' href="{% url 'galleria:imagepage' image.id %}"></a>
            </div>
    {% endfor %}
    {% else %}
    <div>Ei hakutuloksia</div>
    {% endif %}
    
</div>

{% endblock content %}

kuvagalleria/galleria/templates/galleria/upload_page.html
{% extends 'galleria/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <div class='upload-form'>
        <h3>Upload an image</h3>
        <h4>{{message}}</h4>
        <form method="post" enctype="multipart/form-data" class='bootstrap4'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Upload</button>
        </form>
    </div>
</div>

{% endblock content %}